apiVersion: v1
kind: Service
metadata:
  name: city-of-disguise
  namespace: services-demos
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: city-of-disguise

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: city-of-disguise
  namespace: services-demos
spec:
  ingressClassName: nginx
  rules:
  - host: demo.webis.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: city-of-disguise
            port:
              number: 5000

