apiVersion: v1
kind: Service
metadata:
  name: wstud-thesis-libera
  namespace: webisstud
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: wstud-thesis-libera

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wstud-thesis-libera
  namespace: webisstud
spec:
  ingressClassName: nginx
  rules:
  - host: demo.webis.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wstud-thesis-libera
            port:
              number: 5000

